import mongoose from "mongoose";
const doctorSchema = new mongoose.Schema(
    {
        name:{
            type:String,
            required:true,
        },
        salary:{
            type:Number,
            required:true,
        },
        specialization:{
            type:String,
            required:true,
        },
        phoneNumber:{
            type:String,
            required:true,
        },
        email:{
            type:String,
            required:true,
        },
        doctorId:{
            type:String,
            required:true,
        },
        hospital:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Hospital",
            required:true,
        },
        experience:{
            type:Number,
            required:true,
        },
        worksInHospitals:[
            {
                type:mongoose.Schema.Types.ObjectId,
                ref:"Hospital",
            }
        ]
    },
    {timestamps:true}
);
export const Doctor = mongoose.model("Doctor", doctorSchema)